// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD4aFa4K2TQVV7chX_NreUwptUkzd8GKs',
    appId: '1:85550585155:web:5a4e59a46ac6403c110bf6',
    messagingSenderId: '85550585155',
    projectId: 'isave-97876',
    authDomain: 'isave-97876.firebaseapp.com',
    storageBucket: 'isave-97876.appspot.com',
    measurementId: 'G-03D7KNVQK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwgSS3uQl42-4gj1VkrFBq_r4d0VAonBA',
    appId: '1:85550585155:android:4942e49b4baa5d2a110bf6',
    messagingSenderId: '85550585155',
    projectId: 'isave-97876',
    storageBucket: 'isave-97876.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbMkr90ORYZOi8siDsHa9T7_rAnHiLo7E',
    appId: '1:85550585155:ios:29a1a85a2acfa112110bf6',
    messagingSenderId: '85550585155',
    projectId: 'isave-97876',
    storageBucket: 'isave-97876.appspot.com',
    iosBundleId: 'com.example.isaveApplication',
  );
}
