// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfHgljKsQETaqntIYsooKZg-0sC1bBp5k',
    appId: '1:980998008410:web:b6df5cbb0ab6c654bd7263',
    messagingSenderId: '980998008410',
    projectId: 'app-lista-compra-fatec',
    authDomain: 'app-lista-compra-fatec.firebaseapp.com',
    storageBucket: 'app-lista-compra-fatec.appspot.com',
    measurementId: 'G-0DE5VG0YR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPPnO6Dv50BLs2gQabBh7lc_8Waw_17y0',
    appId: '1:980998008410:android:60292bd41046ca96bd7263',
    messagingSenderId: '980998008410',
    projectId: 'app-lista-compra-fatec',
    storageBucket: 'app-lista-compra-fatec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAabjdMMANOJARh-XD8pqQpZSD6nqkzODA',
    appId: '1:980998008410:ios:1fbd38050c71deb4bd7263',
    messagingSenderId: '980998008410',
    projectId: 'app-lista-compra-fatec',
    storageBucket: 'app-lista-compra-fatec.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
